version: '3.2'

services:
  debuggable:
    build: .
    command: npm run debug
    volumes:
      - .:/usr/src/mafio
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      PORT: '3000'
  test-watcher:
    build: .
    command: npm run test:watch
    volumes:
      - type: bind
        source: ./test
        target: /usr/src/mafio/test
        read_only: true
      - type: bind
        source: ./app
        target: /usr/src/mafio/app
        read_only: true
