version: '3'

services:
  debuggable:
    build: .
    command: npm run debug
    volumes:
      - .:/usr/src/mafio
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      PORT: '3000'